# Generated by Django 3.2.12 on 2022-02-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategory', models.CharField(max_length=50)),
                ('Category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alknekit.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('newprice', models.FloatField(default=0)),
                ('oldprice', models.FloatField(default=0)),
                ('mainimage', models.ImageField(default=None, upload_to='static/images/products')),
                ('main', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('Value', models.FloatField(default=None)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alknekit.category')),
                ('subcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alknekit.subcategory')),
            ],
        ),
    ]
