# Generated by Django 3.2.12 on 2022-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='mainimage',
            field=models.ImageField(default=None, upload_to='static/images/products'),
        ),
    ]
