# Generated by Django 3.2.12 on 2022-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0002_auto_20220222_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
