# Generated by Django 3.2.12 on 2022-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0003_products_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Value',
            field=models.FloatField(default=0),
        ),
    ]
