# Generated by Django 3.2.12 on 2022-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0006_alter_products_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Value',
            field=models.FloatField(default=None),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
