# Generated by Django 3.2.12 on 2022-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0007_auto_20220222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
