# Generated by Django 3.2.12 on 2022-02-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0008_alter_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sales',
            new_name='rate',
        ),
    ]
