# Generated by Django 3.2.12 on 2022-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0009_rename_sales_products_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='newprice',
        ),
        migrations.RemoveField(
            model_name='products',
            name='articul',
        ),
        migrations.AddField(
            model_name='products',
            name='oldprice',
            field=models.FloatField(default=0),
        ),
    ]
