# Generated by Django 3.2.12 on 2022-02-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0010_auto_20220222_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
