# Generated by Django 4.0.2 on 2022-02-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alknekit', '0011_alter_products_tittle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
